### ISSUE TITLE
eample code for 16k

### ISSUE THREAD

**Issue by huangxin168** [NeonBohdan/nsnet2-denoiser#1]
It's easy to use, here's an example may be usefull for the comming peoples: 

pip install nsnet2-denoiser

from nsnet2_denoiser import NSnet2Enhancer
import soundfile as sf

data, fs = sf.read(audio_path_wav_16k)
data = denoiser(data, fs)  
sf.write(audio_path_wav_denoised,  data, fs)

**Comment by NeonDaniel** [comment]
It looks like a similar example is already [in README.md](https://github.com/NeonGeckoCom/nsnet2-denoiser/commit/db2c4d77813b9bec1994ddf319bb0a6f22a0d56f)
